### ISSUE TITLE
About Eqn.(12)

### ISSUE THREAD

**Issue by 32l** [LiYingwei/AutoNL#2]
Hi, yingwei, 
     I'm confused about eqn(12),  Xri@XriT is used matmul ? if so, Xri@XriT - Xgt@XgtT 's dimensions  may be not equal.   And what is the purpose of calculate Xatt?  I think we only need to calculate the indicator value to get the corresponding downsample ratio.

**Comment by LiYingwei** [comment]
Thanks for your interest. 

Yes. X<sub>ri</sub>X<sub>ri</sub><sup>T</sup> means matrix multiplication. Here X<sub>ri</sub>X<sub>ri</sub> with shape [HW, C]. Since we only downsample on channel dimension, HW is same for every term in the equation (although C is different). Therefore, for all i, the shape of X<sub>ri</sub>X<sub>ri</sub><sup>T</sup> is [HW, HW]. Figure 4 also illustrates that the output of the matrix multiplication is with shape [HW, HW], which is not influenced by the downsample ratio along channel dimension.

For your second question, you understanding is correct. Compute X<sub>att</sub> is not related to get the downsample ratio, but the model need to compute X<sub>att</sub> for further training or searching. Without the affinity matrix X<sub>att</sub>, we cannot get the output of the NL block, thus cannot get the model output.

**Comment by 32l** [comment]
Thanks for your reply,  still a little confused, If we get the downsample ratio's indicator value both channel and spatial dims, we could calculate NL output according to Eqn(9), is it right?

**Comment by LiYingwei** [comment]
Thanks for your prompt feedback!
Yes. Your understanding is correct. After we get the downsample ratio's indicator, we use Eqn(9) to compute the output. 
We don't actually compute Eqn(11) in our code. Eqn(11) is to conceptually show how we encode the choice of downsample ratios.

**Comment by 32l** [comment]
Ok, I see. Thanks for your info.
